#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    # Put here your user name
#    username: root
#    # Put here your password
#    password: root
#    url: jdbc:mysql://localhost:3306/glutfree_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
#  jpa:
#    #For MySQL 8 uncomment bellow (comment MySQL 5)
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    #For MySQL 5 (innodb dialect below)
##    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#
#servlet:
#  multipart:
#    max-file-size: 1MB
#    max-request-size: 5MB
#    enabled: true
#
#cloudinary:
#  cloud-name: dshodqfsf
#  api-key: 449987992834364
#  api-secret: "${CLOUDINARY_SECRET}"


server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${JDBC_DATABASE_PASSWORD:}
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:

    database-platform: ${SPRING_JPA_DATABASE-PLATFORM:}
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

cloudinary:
  cloud-name: dshodqfsf
  api-key: 449987992834364
  api-secret: "${CLOUDINARY_SECRET}"